### ISSUE TITLE
Not reconnecting, but can create new session

### ISSUE THREAD

**Issue by rainabba** [continuationlabs/node-v8-inspector#13]
I use nodemon for development and so code changes restart the app/debugger and a new uuid is created for debugging. If I hit "Reconnect" on the UI, it doesn't connect to the right session (because it's a new one), but if I close the tab and start a new session using the extension button, it does connect to the new session so it seems the logic is there to find/connect to the new session.

The user-experience would be much nicer if I didn't have to close/re-open constantly and could use the reconnect option (or just have it reconnect automatically).

**Comment by rainabba** [comment]
By the way, thank you for this extension. It is a much appreciated convenience :)

**Comment by cjihrig** [comment]
Thanks for using our little extension :-)

I don't think this is something that can be fixed here. The Reconnect feature that you speak of is not part of this extension, so there is nothing that we can do there.

Starting with Node v6.9.0, the inspector creates a new UUID each time Node starts. This is done for security purposes. When you use this extension, it simply looks up the UUID and then connects to dev tools (saving you a copy+paste from the console window).

There is some discussion in https://github.com/nodejs/node/issues/9185 regarding the new UUIDs, which basically reiterates the problem you're experiencing. You should chime in over there. I think the problem will be sorted out over there soon, and if any changes are required here, I'll make them.
