### ISSUE TITLE
No file tree

### ISSUE THREAD

**Issue by qwelias** [continuationlabs/node-v8-inspector#14]
If I open inspector manually everything is fine, but if it's opened through the extension there is no file tree.

Chrome: Version 54.0.2840.90 (64-bit)
Linux umaze 4.4.0-040400-generic #201601101930 SMP Mon Jan 11 00:32:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

![](https://i.gyazo.com/1cb21ddcc7ab865ff4fde02b3d55e43a.png)

**Comment by cjihrig** [comment]
I can't reproduce this. The file tree is showing up for me in the latest Chrome with the latest version of the plugin (0.9.0).

**Comment by qwelias** [comment]
@cjihrig the problem has gone after some update, but reappeared after a while (0.10.0)
Can you reproduce this? It's really annoying, delaying tab url change works, but it's really weird.

**Comment by cjihrig** [comment]
I still cannot reproduce this.

The proposed fix in #15 seems like a hack. Can you find any documentation that delaying the tab URL change is the correct thing to do? This seems more like an issue with Chrome or DevTools on your system.

**Comment by cjihrig** [comment]
@qwemaze this issue just came through on the Node issue tracker - https://github.com/nodejs/node/issues/10220

Is this what you're experiencing?

**Comment by qwelias** [comment]
@cjihrig no.
Have you tried reproducing it in node7?
I've switched back to 6 recently and problem have gone.

**Comment by cjihrig** [comment]
Just released v0.11.0 of the extension. Maybe give that a shot.

**Comment by qwelias** [comment]
Well, now I have no file tree even with 6th node, but delayed url change still can fix this.
