### ISSUE TITLE
Allow to launch in current window

### ISSUE THREAD

**Issue by Elliot128** [continuationlabs/node-v8-inspector#18]
Hello,

Just installed this and I like using it. Have a use case that I think could benefit the software.

I use nodemon to restart the server on code change. When this happens, node-v8-inspector informs me that I should 'reconnect'.

Reconnecting doesn't work because the server restarted, not simply disconnected. So I have to use the launch button from this tool. Unfortunately, this launches in a new window, leaving behind the disconnected debugger.

I think it would be good to add some sort of functionality to make it easier to initialize a new debugger connection without opening a new tab.

**Comment by cjihrig** [comment]
They are actively working on this in https://github.com/nodejs/node/issues/9185. I'd like to see what comes out of that, keeping in mind that the Inspector is still an experimental feature in Node core.

**Comment by cjihrig** [comment]
Tracking all things related to the Inspector UUID in #24.
