### ISSUE TITLE
Could not launch debugger

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [continuationlabs/node-v8-inspector#19]
Windows 10
Node 7.1.0

cmd: `node --inspect app.js`

extention:
Could not launch debugger
Invalid devtools URL in
[ { "description": "node.js instance", "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/74dec2d8-aca4-4725-85af-f292cb39ad13", "faviconUrl": "https://nodejs.org/static/favicon.ico", "id": "74dec2d8-aca4-4725-85af-f292cb39ad13", "title": "./build/server", "type": "node", "url": "file://C:_localhost_taxi_build_server", "webSocketDebuggerUrl": "ws://127.0.0.1:9229/74dec2d8-aca4-4725-85af-f292cb39ad13" } ]

**Comment by cjihrig** [comment]
Try the latest version of the extension (0.9.0).

**Comment by uMaxmaxmaximus** [comment]
thank you so much, and you do not think what that integration with nodemon?
