### ISSUE TITLE
Open inspector on extention icon click.

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [continuationlabs/node-v8-inspector#20]
Please do so when you click on the icon expansion opened DIRECTLY debugger. And port and host can be changed in the `extension settings`. In 99% of cases, a person when you click on the icon does not change the host and port, and just wants to run the debugger. We have to do 2 clicks instead of one.

**Comment by cjihrig** [comment]
Note to self, or anyone that wants to try to implement this:

Create an [options page](https://developer.chrome.com/extensions/options) that provides the following options:
- Port number (default 9229)
- Host (default localhost)
- A Boolean representing whether or not to launch the debugger directly (default false, use current behavior)

No changes to the existing UI are necessary, although the defaults should be pulled from the new options page.
