### ISSUE TITLE
Doesn't work if the app is running from a remote machine

### ISSUE THREAD

**Issue by thenewvu** [continuationlabs/node-v8-inspector#26]
Hello friends,

Here is my case, I'm running an app in a docker container which is hosted from a remote VPS:
* The app is running with `--inspect=8080`.
* The container exposes port `8080`

So let's assume that the VPS host is 123.30.xxx.xxx, `8080` is exposed to `33129`, it means that the debugger uri should be:

```
https://chrome-devtools-frontend.appspot.com/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=123.30.xxx.xxx:33129/8c3a0c56-74f0-48ee-abca-feecea95f08f
```

... but `http://123.30.xxx.xxx:33129/json/list` responds:

```json
[
  {
    "description": "node.js instance",
    "devtoolsFrontendUrl": "https://chrome-devtools-frontend.appspot.com/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:8080/8c3a0c56-74f0-48ee-abca-feecea95f08f",
    "faviconUrl": "https://nodejs.org/static/favicon.ico",
    "id": "8c3a0c56-74f0-48ee-abca-feecea95f08f",
    "title": "/code/node_modules/pm2/lib/ProcessContainerFork.js",
    "type": "node",
    "url": "file:///code/node_modules/pm2/lib/ProcessContainerFork.js",
    "webSocketDebuggerUrl": "ws://localhost:8080/8c3a0c56-74f0-48ee-abca-feecea95f08f"
  }
]
```

The point is in the `devtoolsFrontendUrl`:

* chrome-devtools-frontend.appspot.com/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=**123.30.xxx.xxx:33129**/8c3a0c56-74f0-48ee-abca-feecea95f08f
* chrome-devtools-frontend.appspot.com/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=**localhost:8080**/8c3a0c56-74f0-48ee-abca-feecea95f08f

Therefore the extension doesn't work in my case. I'm not sure whether debugging remotely in other cases works well or not, please tell me your opinion, I can make a PR when this problem is clear and solved.

Thank you.

**Comment by cjihrig** [comment]
The `/json/list` endpoint comes from the V8 Inspector in Node core. The front end URL makes sense because the Node application is running on `localhost:8080` as far as it knows.

That said, the extension could probably just replace the front end host and port with its own options.
