### ISSUE TITLE
Can't load source files if using `chrome-devtools-frontend.appspot.com`

### ISSUE THREAD

**Issue by thenewvu** [continuationlabs/node-v8-inspector#27]
Hello friends again,

I'm making the PR for #26 and dealing with another issue, the inspector can't load source files if using `chrome-devtools-frontend.appspot.com` but it can if using `chrome-devtools://devtools/remote/`, I have no clue so far.

Doesn't work with:

```
https://chrome-devtools-frontend.appspot.com/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=123.30.xxx.xxx:33068/51121fc9-ebf9-4571-91c6-bf547bfa6db6
```

But works with:

```
chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=123.30.xxx.xxx:33068/51121fc9-ebf9-4571-91c6-bf547bfa6db6
```

My system:

* Arch Linux
* Chrome 55.0.2883.75 (64-bit)
* Node.js v6.9.1 (remote)

I tried to run without extensions but no luck.

Could we change to use `chrome-devtools://devtools/remote/` instead ?

**Comment by cjihrig** [comment]
@eugeneo any clue why the JSON endpoint recommends one URL, while a different one is displayed in the console? Could the two be unified?

**Comment by eugeneo** [comment]
@cjihrig It looks like there are different places for generating the URL (which I need to fix) - https://github.com/nodejs/node/blob/master/src/inspector_socket_server.cc#L89 and https://github.com/nodejs/node/blob/master/src/inspector_socket_server.cc#L318 I do not see any obvious differences, though...

json/list outputs two URLs - devtoolsFrontendUrl (which should be the same as the one printed out to the console) and webSocketDebuggerUrl which is WebSockets URL that does not include Chrome DevTools information.

**Comment by cjihrig** [comment]
It looks like this issue reported here has been fixed somewhere along the line.

In Node's master branch, `/json/list` returns:

```
"devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/401875bf-ab04-408d-8824-6c083546b374"
```

Meanwhile, Node v6.9.2 returns:

```
"devtoolsFrontendUrl": "https://chrome-devtools-frontend.appspot.com/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/d0794108-f805-4870-ac55-1c744cdfb578"
```

The joys of working with unofficial APIs :-)

**Comment by eugeneo** [comment]
This difference stems from the V8 Inspector update - Node 6.9.2 was based on an inspector version that was before the move to the V8 repository and worked with a specific Chrome DevTools version. Newer node uses V8 inspector imported from the V8 repository that exposes a stable protocol that allows using DevTools bundled with Chrome (e.g. as newer versions of Chrome are released, newer devtools will be used).

**Comment by cjihrig** [comment]
Thanks for the clarification @eugeneo. I've got a patch that I'm in the process of testing across Node versions. Seems to work in v6.3.0 (the first version with the inspector) to always use `chrome-devtools://devtools/bundled/inspector.html`.

**Comment by eugeneo** [comment]
--debug-brk will not work. The message that informed Node that frontend is ready had changed. I would expect some other random failures as some other messages were normalized.

**Comment by cjihrig** [comment]
Interesting. `--inspect --debug-brk` works for me in v6.3.0 with that fix. Do you have any suggestions that fix this issue across different versions? You can take a look at what I've got in https://github.com/cjihrig/node-v8-inspector/commit/a189d54614ec74fb1ed8e21e2d460ad1e6e77dd5.

**Comment by cjihrig** [comment]
There was a regex bug in that commit. When I fix it, I see that you're correct about it not working.

**Comment by eugeneo** [comment]
This is what changed:
https://github.com/nodejs/node/commit/354166c061812938671c46655f45ad547617f1f2#diff-8d16a44747475ef748bab83e5f9dade2L595 

I do not have a detailed list of changes between old protocol and stable one - this is the only change that was required in the Node itself.
