### ISSUE TITLE
Improve UI + polling launch scenario

### ISSUE THREAD

**Issue by cjihrig** [continuationlabs/node-v8-inspector#31]
Steps to reproduce:
- Open settings page.
- Uncheck `Quick launch using default settings`.
- Check `Open devtools whenever the node inspector is running`.
- Save settings.
- Make sure Node is not running.
- Click the extension button to open the UI.
- Click "Launch V8 Inspector".
- Start Node. Notice that the DevTools is not launched.

**Comment by cjihrig** [comment]
cc: @johnjbarton if you're interested.

**Comment by johnjbarton** [comment]
Great, thanks!
