### ISSUE TITLE
After Chrome update Inspector don't work

### ISSUE THREAD

**Issue by kozlovital** [continuationlabs/node-v8-inspector#32]
After Chrome update to version 64.0.3282.186 Node.js V8 Inspector after connecting immideatly disconnect with the error: Debugging connection was closed. Reason: WebSocket disconnected"
Connect to localhost 9229

**Comment by cjihrig** [comment]
I can't reproduce with Node 8.10.1 and Chrome 65.0.3325.181. If you can provide more concrete steps to reproduce, I can take a look.
