### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by 1j01** [continuationlabs/node-v8-inspector#7]
I had to use Inspect Popup to get the actual error messages behind what was given.

First I got:

```
Could not launch debugger
Failed to fetch
```

After realizing I was[ pasting in a URL](https://github.com/continuationlabs/node-v8-inspector/issues/8) where just a host is needed I got the same error after a longer delay.
I used Inspect Popup to see the actual error message which was
`GET http://audio-editor-a1j01.c9.io:8083/json/list net::ERR_CONNECTION_TIMED_OUT`
and eventually looked at the description on the webstore and realized I needed to switch (back) to using `--inspect`

Then I got:

```
Could not launch debugger
Invalid configuration data at http://audio-editor-a1j01.c9.io:8082/json/list
```

The real error was:
`GET http://audio-editor-a1j01.c9.io:8082/json/list 503 (Service Unavailable)`

Eventually I tried changing my script from
`"coffee --nodejs \"--inspect=8082 --debug-brk=8083\" build.coffee"`
to just `"coffee --nodejs \"--inspect=8082 --debug-brk\" build.coffee`
...and it finally worked!

Since this is a developer-facing tool, you should feel free to show the actual error messages in addition to any friendly messages for specific cases.

**Comment by cjihrig** [comment]
I'll take a PR if you want to put something together.

**Comment by 1j01** [comment]
I would like to do this, but I don't know when I'll get around to it.

**Comment by cjihrig** [comment]
We can leave this open for a while and see if anyone picks it up.

**Comment by cjihrig** [comment]
Closing. If anyone wants to pick this up, feel free and I can reopen.
